# Generated by Django 5.0.4 on 2024-07-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_posts', '0004_answer_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answers',
        ),
    ]
